CREATE TABLE SPEAKER_PROFILE
(
   UUID VARCHAR(40) NOT NULL,
   NAME VARCHAR(20) NOT NULL,
   PRIMARY KEY (UUID)
);

INSERT INTO SPEAKER_PROFILE(UUID, NAME)
   VALUES('5ef9d03c-04ea-46ba-afff-ed98187ff775', 'Juergen');